version: '3'
services:
    mssqlserver:
        image: 'mcr.microsoft.com/mssql/server:2022-latest'
        environment:
            - SA_PASSWORD=${SA_PASSWORD}
            - ACCEPT_EULA=Y
        ports:
            - '1433:1433'
